### ISSUE TITLE
Instructions on how to use

### ISSUE THREAD

**Issue by MtnBiker** [MuhammetDilmac/Html2Docx#9]
Asking for how to use from the irb prompt. Or in a small app.

I'm probably too new to Ruby to figure this out.

Because this looks like a useful app.

Thank you.

**Comment by MuhammetDilmac** [comment]
Hello @MtnBiker,
First of all thank you for your interest.

Did you read the wiki page? The wiki page contains example usage :)
[Paragraph Usage](https://github.com/MuhammetDilmac/Html2Docx/wiki/Paragraph-Usage)
[Heading Usage](https://github.com/MuhammetDilmac/Html2Docx/wiki/Heading-Usage)

End of page has example usage. This code working on irb prompt :)

I'm working new features;
* Table
* Image
* Links
* Table of contents

I will add them soon :)

**Comment by MtnBiker** [comment]
Merhaba Muhammet

I did look, but don’t know what to do with the examples.  Doesn’t make sense to me as HTML—what is `Html2Docx.render(options)` and doesn’t make sense as Ruby or RoR.

Thank you

Greg

**Comment by MuhammetDilmac** [comment]
Hello @MtnBiker,
(Sorry, i forget dependencies declaring runtime dependency :/  I fix this next version. You use following commands when i fix it)
Open your shell then run following commands; (Please change options[:output] value for your output directory)
```bash
gem install nokogiri
gem install rubyzip
gem install Html2Docx
irb
require 'Html2Docx'
options = {}
options[:output] = '/home/YOUR_USER_NAME/Output.docx'
options[:html] = <<-HTML
<!DOCTYPE html>
<html>
<body>
  <h1>Html2Docx</h1>
  <h2>Usage Example</h2>
  <p>Hello MtnBiker,</p>
  <p style="text-align: justify; text-indet: 15px;">This example usage for <strong>Htm2Docx</strong>. <strong>Html2Docx</strong> your <i>html</i> output converting <u>Docx</u> format. </p>
  <p style="text-align: justify; text-indent: 25px ; background-color: #cccccc;">For example please see end of comment :)</p>
  <p style="text-align: right;">Thanks :)</p>
</body>
</html>
HTML

Html2Docx.render(options)
```

When all command is executed. You have a new file; /home/YOUR_USER_NAME/Output.docx

Html Code
![HTML Code](http://i.imgur.com/TUc2b6t.png)

HTML Result
![HTML Result](http://i.imgur.com/ouOTVIu.png)

Ruby Code
![Ruby Code](http://i.imgur.com/8BYlYy2.png)

Ruby Result
![Ruby Result](http://i.imgur.com/xssW2DP.png)

**Comment by MtnBiker** [comment]
Hi

I got this working as a script test.rb at the top level of your GitHub project.:

#!/usr/bin/env ruby
load 'lib/Html2Docx.rb'
options = {}
options[:output] = '/Users/gscar/Documents/Ruby/Html2Docx/test.docx'
options[:html] = <<-HTML
<!DOCTYPE html>
<html>
<body>
  <h1>Html2Docx</h1>
  <h2>Usage Example</h2>
  <p>Hello MtnBiker,</p>
  <p style="text-align: justify; text-indet: 15px;">This example usage for <strong>Htm2Docx</strong>. <strong>Html2Docx</strong> your <i>html</i> output converting <u>Docx</u> format. </p>
  <p style="text-align: justify; text-indent: 25px ; background-color: #cccccc;">For example please see end of comment :)</p>
  <p style="text-align: right;">Thanks :)</p>
</body>
</html>
HTML

Html2Docx.render(options)
==========

I had to make all the requires in Html2Docx.rb absolute file references, but otherwise worked. Haven’t been doing Ruby lately so forgot why that was needed.

If I were going to use this regularly I’d add a file picker for the HTML except not sure how it would handle the <head>

Tried it on a page with JS and not surprisingly didn’t produce anything.

Thank you. Keep up the effort.

Greg

**Comment by MuhammetDilmac** [comment]
Hi @MtnBiker,
May be add support html file picker :) 
JS not handling :) Docx not supporting js :)

**Comment by MtnBiker** [comment]
Good
Greg
